baseURL = 'https://vaqm2.github.io/'
languageCode = 'en-us'
title = 'Vivek Appadurai'
theme = 'hello-friend-ng'

PygmentsCodeFences = true
PygmentsStyle = "monokai"

[params]
  homeSubtitle = "Bioinformatician | Software Developer | Data Tinkerer"

  # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/vaqm2"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/vivek-appadurai-54a622192/"

  [[params.social]]
    name = "googlescholar"
    url  = "https://scholar.google.com/citations?user=sUD1UocAAAAJ&hl=en&oi=ao"

[menu]
  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 10
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/resume/"
    weight     = 20
  [[menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "/publications/"
    weight     = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true